spring:
  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
    url: jdbc:postgresql://${POSTGRES_PROD_HOST}:${POSTGRES_PROD_PORT}/${ATTENDANCE_SERVICE_PROD_DB}
    username: ${POSTGRES_PROD_USER}
    password: ${POSTGRES_PROD_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate

#  flyway:
#    enabled: true
#    url: jdbc:postgresql://${POSTGRES_PROD_HOST}:${POSTGRES_PROD_PORT}/${ATTENDANCE_SERVICE_PROD_DB}
#    user: ${POSTGRES_PROD_USER}
#    password: ${POSTGRES_PROD_PASSWORD}
#    locations: classpath:db/migration
#    validate-migration-naming: true

server:
  port: 9093

# Secret key
jwt:
  secret:
    key: 8KvVu4Bn2KwBNX1MdnXY6VaRVLekVxurk3aaJxnzdCuZL6AHEL0EnnAOYLZtHWUr
  access:
    token:
      expiration: 1800000 # 30 min in milliseconds for token expiration time
  refresh:
    token:
      expiration: 604800000 # 7 days in milliseconds

logging:
  level:
    root: warn
